name: release packet

on:
  push:
    branches: 
      - develop
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: XEngine_ProxyServiceApp-x64-Ubuntu
          path: ./
      - name: Display structure of downloaded files
        run: ls -al