name: release packet

on:
  push:
    branches: 
      - develop
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Download linuxbuild
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: linuxbuild.yml
          workflow_conclusion: success
          check_artifacts: false
          skip_unpack: true
          if_no_artifact_found: fail
          path: ./
      - name: Download macbuild
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: macbuild.yml
          workflow_conclusion: success
          check_artifacts: false
          skip_unpack: true
          if_no_artifact_found: fail
          path: ./
      - name: Download msbuild
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: msbuild.yml
          workflow_conclusion: success
          check_artifacts: false
          skip_unpack: true
          if_no_artifact_found: fail
          path: ./

      - name: Display structure of downloaded files
        run: ls -al ./