name: release packet

on:
  push:
    branches: 
      - develop
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Download linuxbuild
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: linuxbuild.yml
          workflow_conclusion: success
          check_artifacts: false
          skip_unpack: true
          if_no_artifact_found: fail
          path: ./
      - name: Download macbuild
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: macbuild.yml
          workflow_conclusion: success
          check_artifacts: false
          skip_unpack: true
          if_no_artifact_found: fail
          path: ./
      - name: Download msbuild
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: msbuild.yml
          workflow_conclusion: success
          check_artifacts: false
          skip_unpack: true
          if_no_artifact_found: fail
          path: ./

      - name: Display structure of downloaded files
        run: ls -al ./

        # 检出代码并包含标签
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      # 获取最新的标签并提取 X 部分
      - name: Get current version and increment X
        id: version
        run: |
          CURRENT_TAG=$(git describe --tags --abbrev=0)
          VERSION_PREFIX=$(echo $CURRENT_TAG | sed -E 's/V([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)/V\1/')
          X=$(echo $CURRENT_TAG | sed -E 's/V([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)/\2/')
          NEXT_X=$((X + 1))
          NEXT_TAG="${VERSION_PREFIX}.${NEXT_X}.0.1001"
          echo "New tag will be: $NEXT_TAG"
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV

      # 创建并推送新的 Git 标签
      - name: Create and push new tag
        run: |
          git tag ${{ env.NEXT_TAG }}
          git push origin ${{ env.NEXT_TAG }}
        
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ env.NEXT_TAG }}
          files: |
            XEngine_ProxyServiceApp-x64-Mac.zip
            XEngine_ProxyServiceApp-x64-Ubuntu.zip
            XEngine_ProxyServiceApp-x64-Windows.zip
            XEngine_ProxyServiceApp-x86-Windows.zip